### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [frankjoke/ioBroker.radar#18]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by frankjoke** [comment]
Ingo, who is in charge of Admin-3 and the includes there?
I have problems with the materialize version which iot uses. It seems to be a pretty old one which is not compatible with the documentation.

On top of that the adpater.css changes  some items dramatically so that functionality of whole materialize and iven some standard normal html does not work anymore.

The reason is that the css does not work on own adapter classes but changes some classes from materialize or even html. this is very bad practice. We should not change for example 'h4' or 'table' appearance for all because one usage in the adapter needs it different, we need to use classes or id's to change only the occurnces we need.

On top of that I cannot use the library which is on ../../... because it does not work with my code which was using 0.100.2 of Materialie (the last official version from autumn last year). 
I need to include it myself again which is even worse.

I think it's time for a cleanup, I found for all libraries (jquery, jquery-ui, ...) 2-3 version in the library.  I think we should put one version into the library (without the exact version name).

p.s.: one side effect of above is also that I have different appearance and problems on different test system.

For example, I had systems where I installed admin-beta and others where I went only now from old 2.09 to admin 3.1.5. The appearance of adapter config is now different between the two!

**Comment by Apollon77** [comment]
Best is to bring this up in the referenced forum thread ... i can point Bluefox on it directly after you posted there ... then also the other adapter devs can follow and participate

**Comment by Apollon77** [comment]
Were you able to solve your questions?

**Comment by frankjoke** [comment]
Not really, had some other work this week and used yesterday to debug my adapter because I identified a big change in Admin 2.0.9 to 3.1..x which renders my tab.html useless! The problem started some time after 3.1 was released normally and Beta was gone, I do not get state and object subscriptions if the tab is on screen, only if it is in background! I will do a post when I have final information about cause but I had to go back to 2.0.9 on development machine to allow further development and use 3.1.x only on test machine.

I currently only implemented changes on broadlink, but need to re-check all others...

**Comment by neorulez** [comment]
Hi Frank,

I've got the very same problem:

radar.0 | 2018-02-26 17:05:03.865 | warn | Scan devices returned error: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null at pSeriesP (/opt/iobroker/node_modules/iobroker.radar/radar.js:56:20) at Promise.all.pExec.then
-- | -- | -- | --

Additionally, I can't use radar on my Raspberry Pi 3 because from time to time the whole system hangs and isn't reachable in the network.

Any update or ideas?

**Comment by thomasblass** [comment]
This sounds really bad. I just installed radar on Admin 3.2 and cannot even add entries to the table because the "Save" Button is greyed out, and even if it is clickable it does not save. 
Is there another way to add entries to get radar working?

**Comment by frankjoke** [comment]
Hi Thomas! I have one system with Admin 3.2 and Radar running and tested, it's working for me.
The only thing is that you need to scroll down to see the 'add line' button to add a new line.
But otherwise adding/deleting/changing entries work.

**Comment by frankjoke** [comment]
I added Admin V3 to V1.2.0 which is on Github in test now!

**Comment by Messiahs** [comment]
Ty Frank 👍
