### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [frankjoke/ioBroker.radar#28]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by frankjoke** [comment]
Hi ldittmar81!
I just work on 2.0 version of the adapter and will try to include the 'compact' feature.
Where can I find a description how to setub a test version of ioBroker with the beta version of 2.0 js-controller and, if necessary new admin because I believe also Admin needs to be changed to select compact mode for each adapter.

**Comment by frankjoke** [comment]
This adapter uses noble and cannot support compact mode because it cannot close all open drivers or sockets (due to bad programming in noble). I close this issue therefore. p.s.: The same will be true for radar2-adapter and most probably the ble-adapter as well!
